var provincias=[
    {
        "nombre":"Guayas",
        "ciudades":[
            {
                "nombre":"Guayaquil"
            },
            {
                "nombre":"Daule"
            },
            {
                "nombre":"Durán"
            }
        ]
    },
    {
        "nombre":"Pichincha",
        "ciudades":[
            {
                "nombre":"Quito"
            },
            {
                "nombre":"Cayambe"
            },
            {
                "nombre":"Mejía"
            }
        ]
    },
    {
        "nombre":"Los Rios",
        "ciudades":[
            {
                "nombre":"Babahoyo"
            },
            {
                "nombre":"Huaquillas"
            },
            {
                "nombre":"Quevedo"
            }
        ]
    },
    {
        "nombre":"Manabí",
        "ciudades":[
            {
                "nombre":"Portoviejo"
            },
            {
                "nombre":"Manta"
            },
            {
                "nombre":"Paján"
            },
            {
                "nombre":"Jipijapa"
            }
        ]
    }
]